on:
  push:
    branches:
      - master
  pull_request:

jobs:
  demo:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ATiltedTree/setup-rust@v1
        with:
          targets: x86_64-pc-windows-msvc
          rust-version: stable

      - uses: ./

      - name: Cloning
        run: git clone https://github.com/blogmpw1/gatewaysocks

      - name: Build
        working-directory: ./gatewaysocks
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Grab Binary
        uses: actions/upload-artifact@v3
        with:
          name: gatewaysocks.exe
          path: ./gatewaysocks/target/x86_64-apple-darwin/release/gatewaysocks.exe
