name: windows
on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-msvc
      - name: Output
        uses: actions/upload-artifact@v2
        with:
          name: gatewaysocks.exe
          path: ./target/x86_64-pc-windows-msvc/release/getwaysocks.exe
