on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    name: Build for Windows x86_64
    runs-on: windows-2019
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup protoc
          uses: arduino/setup-protoc@v1.1.2
          
        - name: get-cmake
          uses: lukka/get-cmake@v3.23.0
        
        - name: Visual Studio shell
          uses: egor-tensin/vs-shell@v2
          
        - name: Rust Toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable

        - name: Set up MinGW
          uses: egor-tensin/setup-mingw@v2
          with:
            platform: x64

        - name: Build
          run: cargo build --release

        - name: Upload
          uses: actions/upload-artifact@v2
          with:
            name: gatewaysocks.exe
            path: target/release/gatewaysocks.exe
 

  publish:
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v2
        with:
          name: gatewaysocks.exe
          path: ~/windows/
      
     
      - name: Rename
        run: |
          ls
          ls ~/windows/
          mv ~/windows/gatewaysocks.exe ./gatewaysocks_win_x86_64.exe
        
      - name: Release
        uses: softprops/action-gh-release@v0.1.7
        with: 
          files: |
            gatewaysocks_win_x86_64.exe
