name: Build rust on windows, mac osx, linux x86_64
#on: [push]
on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: build
        run: cargo build --release --all-features
      - name: release
        uses: softprops/action-gh-release@v1
        # only do this step when there's a git tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/gatewaysocks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-win:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: build
        run: cargo build --release --all-features
      - name: release
        uses: softprops/action-gh-release@v1
        # only do this step when there's a git tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/gatewaysocks.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
